# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ocRuFfUatWUJiaesxwpc5tXgNN__mrsC
"""

import gradio as gr
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt


nltk.download('stopwords')
nltk.download('wordnet')


stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = re.sub("[^a-zA-Z]", " ", str(text))
    tokens = text.lower().split()
    tokens = [lemmatizer.lemmatize(w) for w in tokens if w not in stop_words and len(w) > 2]
    return " ".join(tokens)

def analyze(file):
    try:
        df = pd.read_csv(file.name)
    except Exception as e:
        return "Error reading file: " + str(e), None

    if 'sentence' not in df.columns:
        return "CSV must contain a 'sentence' column.", None

    sentences = df['sentence'].dropna().tolist()
    texts_clean = [preprocess(s) for s in sentences]


    vectorizer = TfidfVectorizer(max_df=0.7, min_df=1)
    X = vectorizer.fit_transform(texts_clean)

    n_clusters = 4
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    labels = kmeans.fit_predict(X)
    df['cluster'] = labels


    custom_names = ["politics", "sports", "entertainment", "technology"]
    cluster_map = {i: custom_names[i] for i in range(n_clusters)}
    df['cluster_name'] = df['cluster'].map(cluster_map)


    grouped_sentences = df.groupby("cluster_name")['sentence'].apply(list).to_dict()
    result_output = ""
    for category, group_sentences in grouped_sentences.items():
        result_output += f"### {category.capitalize()} ({len(group_sentences)} sentences)\n"
        for sent in group_sentences[:10]:  # Limit to 10 per category
            result_output += f"- {sent.strip()}\n"
        result_output += "\n"


    tsne = TSNE(n_components=2, random_state=42)
    X_2d = tsne.fit_transform(X.toarray())

    fig, ax = plt.subplots(figsize=(6, 4))
    color_map = [cluster_map[label] for label in labels]
    colors = {'politics': 0, 'sports': 1, 'entertainment': 2, 'technology': 3}
    scatter = ax.scatter(X_2d[:, 0], X_2d[:, 1], c=[colors[c] for c in color_map], cmap='tab10')
    ax.set_title("t-SNE Visualization of Clusters")
    ax.set_xlabel("Component 1")
    ax.set_ylabel("Component 2")


    handles = [plt.Line2D([0], [0], marker='o', label=name,
               color='w', markerfacecolor=plt.cm.tab10(colors[name]), markersize=6)
               for name in custom_names]
    ax.legend(handles=handles, title="Categories")

    return result_output, fig


iface = gr.Interface(
    title="Document Clustering App",
    description="Upload a CSV file with a 'sentence' column. The app will classify sentences into clusters like politics, sports, entertainment, and technology.",
    fn=analyze,
    inputs=gr.File(label="Upload your sentences.csv"),
    outputs=[
        gr.Markdown(label="Clustered Sentences"),
        gr.Plot(label="t-SNE Cluster Visualization")
    ]
)

if __name__ == "__main__":
    iface.launch()